Updated README.md
metakgp/iitkgp-erp-auto-login pull request #7
Opened 2024-06-16 08:30 UTC by Bikram-ghuku

Fixes: #3

2024-06-16 14:11 UTC, proffapt commented
Request for review once done.

2024-06-16 14:22 UTC, Bikram-ghuku commented
> Request for review once done.

Review pls

2024-06-16 16:23 UTC, proffapt requested changes
- [ ] Add LICENSE from the readme.md repo as well
- [ ] Take inspiration from [ferp](https://github.com/proffapt/fERP)      
      <img width="899" alt="image" src="https://github.com/metakgp/iitkgp-erp-auto-login/assets/86282911/a2cf7ae8-50e2-4a2e-a971-621c06723a3b">
      This will be the real installation part with those "add to firefox" "add to chrome" images as welll.

2024-06-16 16:23 UTC, proffapt commented on README.md
> +  - [Supports](#supports)
```suggestion
```

2024-06-16 16:23 UTC, proffapt commented on README.md
> +    ·
```suggestion
```

2024-06-16 16:23 UTC, proffapt commented on README.md
> +    * any `*nix`[`GNU+Linux` and `Unix`]
```suggestion
```

2024-06-16 16:23 UTC, proffapt commented on README.md
> +## Getting Started
Rename this section to configuring the development environment or something similar and smaller. or just Building from source.

2024-06-17 11:34 UTC, Bikram-ghuku commented
The links to the chrome and firefox are the links to the old versions...

2024-06-17 14:46 UTC, proffapt requested changes
- [ ] Add manual installation steps, as shown in [fERP](https://github.com/proffpat/ferp)
- [ ] Move those store installation icons below the text (below the extension logo)
- [ ] Edit that main image and mask the github URL

2024-06-17 14:46 UTC, proffapt commented on README.md
> +     git clone https://github.com/siddsarkar/iitkgp-erp-auto-login-extension.git
```suggestion
     git clone https://github.com/metakgp/iitkgp-erp-auto-login.git
```

Update it in all other places too.

2024-06-17 14:46 UTC, proffapt commented on README.md
> +    <a href="https://github.com/proffapt/iitkgp-erp-auto-login/issues">Request Feature / Report Bug</a>
```suggestion
    <a href="https://github.com/metakgp/iitkgp-erp-auto-login/issues">Request Feature / Report Bug</a>
```

2024-06-17 14:46 UTC, proffapt commented on README.md
> +<!-- UPDATE -->
```suggestion

```

2024-06-17 14:46 UTC, proffapt commented on README.md
> +     cd iitkgp-erp-auto-login-extension
```suggestion
     cd iitkgp-erp-auto-login
```

2024-06-17 14:46 UTC, proffapt commented on README.md
> +### Building From Source
```suggestion
```

2024-06-17 14:46 UTC, proffapt commented on README.md
> +- #### Development
```suggestion
### Development
```

2024-06-17 14:46 UTC, proffapt commented on README.md
> +- #### Deployment
```suggestion
### Deployment
```

2024-06-17 14:46 UTC, proffapt commented on README.md
> +    <img src="https://blog.mozilla.org/addons/files/2020/04/get-the-addon-fx-apr-2020.svg" alt="ERP Auto Login - IITKGP logo" height="58">
```suggestion
    <img src="https://blog.mozilla.org/addons/files/2020/04/get-the-addon-fx-apr-2020.svg" alt="ERP Auto Login - IIT KGP logo" height="58">
```

2024-06-17 14:46 UTC, proffapt commented on README.md
> +    <img src="https://storage.googleapis.com/web-dev-uploads/image/WlD8wC6g8khYWPJUsQceQkhXSlv1/UV4C4ybeBTsZt43U4xis.png" alt="ERP Auto Login - IITKGP logo">
```suggestion
    <img src="https://storage.googleapis.com/web-dev-uploads/image/WlD8wC6g8khYWPJUsQceQkhXSlv1/UV4C4ybeBTsZt43U4xis.png" alt="ERP Auto Login - IIT KGP logo">
```

2024-06-17 14:46 UTC, proffapt commented on README.md
> +ERP Auto Login is a chrome/ firefox extension which can be added to the browser. The extension stores the users confidentials like username, password and security questions and fills them up automati
```suggestion
ERP Auto Login is a browser extension supporting both chrome and firefox. The extension stores the users confidentials like username, password and security questions and fills them up automatically whenever the user opens the ERP. It also sends the OTP to the email, the user only need to fill up the OTP and can login.
```

2024-06-17 14:46 UTC, proffapt commented on README.md
> +- [Additional documentation](#additional-documentation)
Update this, doesn't look like this is updated :)

2024-06-17 14:46 UTC, proffapt commented on README.md
> +  <!-- UPDATE -->
```suggestion
```

2024-06-17 14:46 UTC, proffapt commented on README.md
> +  <h3 align="center">ERP Auto Login - IITKGP</h3>
```suggestion
  <h3 align="center">ERP Auto Login - IIT KGP</h3>
```

2024-06-19 13:35 UTC, proffapt approved these changes

2024-06-19 13:36 UTC, merged